name: build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      run: |
        yarn install
        yarn docs:build
        
    - name: deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        cd docs/.vuepress/dist
        git config --global user.email "14hhan@gmail.com"
        git config --global user.name "hywn"
        git init
        git add -A
        git commit -m 'deploy vuepress'
        git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
